# Generated by Django 4.1.3 on 2022-12-09 10:48

from django.db import migrations, models
import rest_application.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "personal_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[rest_application.models.valid_personal_id],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, validators=[rest_application.models.valid_name]
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=50, validators=[rest_application.models.valid_name]
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        validators=[rest_application.models.valid_age]
                    ),
                ),
            ],
        ),
    ]
