# Generated by Django 4.1.3 on 2022-12-07 10:38

from django.db import migrations, models
import rest_application.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile/profile_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50, validators=[rest_application.models.valid_name]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50, validators=[rest_application.models.valid_name]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, validators=[rest_application.models.valid_personal_id]),
        ),
    ]
